baseURL = "https://jonasblasques.com/"
languageCode = "en-us"
title = "Professional Website"
theme = "github-style"

[params]
  author = "João Blasques (Jonas)"
  description = "Professional Website"
  github = "your-github-username"
  # Optional settings
  twitter = ""
  linkedin = "www.linkedin.com/in/joaoblasques"
  email = "joaoeduardoblasques@gmail.com"
  avatar = "/images/avatar.png"
  favicon = "/images/favicon.ico"

[params.gitalk]
  owner = "" # Your GitHub ID
  repo = "" # The repo to store comments
  clientId = "" # Your client ID
  clientSecret = "" # Your client secret
