baseURL = "https://joaoblasques.github.io/"
languageCode = "en-us"
title = "João Blasques | AI-Enabled Data Engineer"
theme = "github-style"
publishDir = "docs"

[params]
  author = "João Blasques (Jonas)"
  description = "Professional website of João Blasques, AI-Enabled Data Engineer"
  github = "joaoblasques"
  # Optional settings
  twitter = ""
  linkedin = "https://www.linkedin.com/in/joaoblasques"
  email = "joaoeduardoblasques@gmail.com"
  avatar = "/images/avatar.jpg"
  favicon = "/images/favicon.ico"
  headerIcon = "images/github-mark-white.png"

# Comment out Gitalk since it's not being used
# [params.gitalk]
#   owner = "" # Your GitHub ID
#   repo = "" # The repo to store comments
#   clientId = "" # Your client ID
#   clientSecret = "" # Your client secret
