name: Simple Hugo Deployment
# Simplified workflow for GitHub Pages deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

# Set permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single job that handles both build and deploy
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true
      
      - name: Build
        run: |
          hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: 'Deploy site from ${{ github.sha }}'
