name: Deploy Hugo site to Pages
# Updated workflow with robust error handling, artifact retention, and explicit build verification

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true
      
      - name: List directories for debugging
        run: |
          ls -la
          echo "Theme directory contents:"
          ls -la themes/
          echo "GitHub Style theme contents:"
          ls -la themes/github-style || echo "Theme directory doesn't exist"
      
      - name: Build with Hugo
        id: build
        continue-on-error: false
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
          echo "HUGO_BUILD_STATUS=success" >> $GITHUB_ENV
      
      - name: Verify build output
        if: env.HUGO_BUILD_STATUS == 'success'
        id: verify
        run: |
          echo "Public directory contents:"
          ls -la public/ || { echo "Public directory doesn't exist"; exit 1; }
          if [ ! -f "public/index.html" ]; then
            echo "Error: index.html is missing from the build output"
            exit 1
          fi
          echo "Build verification successful"
          echo "BUILD_VERIFIED=true" >> $GITHUB_ENV
      
      - name: Upload artifact
        if: env.BUILD_VERIFIED == 'true'
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          retention-days: 7
          
      - name: Save build info
        if: success()
        run: |
          echo "BUILD_ID=${{ github.run_id }}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=github-pages" >> $GITHUB_ENV
          echo "::notice::Build successful, artifact saved with retention of 7 days"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      # Environment is configured through GitHub settings
    runs-on: ubuntu-latest
    needs: build
    if: success()
    concurrency:
      group: "pages-deploy"
      cancel-in-progress: false
    steps:
      - name: Wait for artifact to be available
        run: |
          echo "Waiting for artifact to be available..."
          sleep 10

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        # Add explicit wait-for-pages-build parameter for better integration with GitHub Pages
        with:
          timeout: 600000  # 10 minutes in milliseconds
          
      - name: Verify deployment
        if: steps.deployment.outcome == 'success'
        run: |
          echo "Deployment successful!"
          echo "Site is now available at: ${{ steps.deployment.outputs.page_url }}"
